jobs:
  build:
    machine:
      image: 'ubuntu-1604:201903-01'
    steps:
      - run: 'sudo apt-get install -y libgstreamer1.0-0 gstreamer1.0-plugins-base gstreamer1.0-plugins-good gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly gstreamer1.0-libav gstreamer1.0-doc gstreamer1.0-tools gstreamer1.0-x gstreamer1.0-alsa gstreamer1.0-gl gstreamer1.0-gtk3 gstreamer1.0-qt5 gstreamer1.0-pulseaudio'
      - run: 'sudo apt-get install -y gstreamer1.0'
      - checkout
      - matlab/install
      - matlab/run-tests:
          test-results-junit: test-results/matlab/results.xml
      - store_test_results:
          path: test-results

orbs:
  matlab: mathworks/matlab@0.1.1
version: 2.1
