jobs:
  build:
    machine:
      image: 'ubuntu-1604:201903-01'
    steps:
      - checkout
      - matlab/install
      - matlab/run-command:
          command: runtests
orbs:
  matlab: mathworks/matlab@0.1.1
version: 2.1
