jobs:
  build:
    machine:
      image: 'ubuntu-1604:201903-01'
    steps:
      - checkout
      - run: 'sudo apt-get install -y gstreamer1.0'
      - matlab/install
      - matlab/run-tests:
          test-results-junit: test-results/matlab/results.xml
      - store_test_results:
          path: test-results

orbs:
  matlab: mathworks/matlab@0.1.1
version: 2.1
